name: Prerelease
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0" # At 00:00 on Sunday (weekly)
env:
  BASE: /next/
  USER: study
  SERVER: studyathome.technikum-wien.at
  DEST: /var/www/html/asterics-web-devwindows/rehatec/next
  SCP_OPTS: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: rehabilitationstechnik
          path: docs/.vitepress/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      PASS: ${{ secrets.USER_KEY }}
    steps:
      - name: Download Build Result
        uses: actions/download-artifact@v3
        with:
          name: rehabilitationstechnik
      # DANGER:
      # - name: Delete Content from Server
      #   run: sshpass -p ${PASS} ssh ${SSH_OPTS} ${USER}@${SERVER} "echo rm -rf ${DEST}/*"
      - name: Upload Build to StudyATHome Server
        run: sshpass -p ${PASS} scp ${SSH_OPTS} -r * ${USER}@${SERVER}:${DEST}/
